module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  collectCoverageFrom: ["**/*.{ts,tsx}", "!**/*.d.ts", "!**/node_modules/**"],
  testMatch: ["**/?(*.)+(spec|test).(j|t)s?(x)"],
  testPathIgnorePatterns: ["/node_modules/"],
  transform: {
    "node_modules/variables/.+\\.(j|t)sx?$": "ts-jest",
    "^.+\\.tsx?$": [
      "ts-jest",
      {
        isolatedModules: true,
      },
    ],
  },
  transformIgnorePatterns: ["node_modules/(?!variables/.*)"],

  moduleNameMapper: {
    "@connection/(.+)": "<rootDir>/src/connection/$1",
    "@contexts/(.+)": "<rootDir>/src/contexts/$1",
    "@localStorage/(.+)": "<rootDir>/src/localStorage/$1",
    "@router/(.+)": "<rootDir>/src/router/$1",
    "@validates/(.+)": "<rootDir>/src/validates/$1",
    "@enums/(.+)": "<rootDir>/src/enums/$1",
    "@constants/(.+)": "<rootDir>/src/constants/$1",
    "@drawers/(.+)": "<rootDir>/src/drawers/$1",
    "@enums/(.+)": "<rootDir>/src/enums/$1",
    "@features/(.+)": "<rootDir>/src/features/$1",
    "@localStorage/(.+)": "<rootDir>/src/localStorage/$1",
    "@mappers/(.+)": "<rootDir>/src/mappers/$1",
    "@mappers/(.+)": "<rootDir>/src/mappers/$1",
    "@modals/(.+)": "<rootDir>/src/modals/$1",
    "@models/(.+)": "<rootDir>/src/models/$1",
    "@pages/(.+)": "<rootDir>/src/pages/$1",
    "@pagination/(.+)": "<rootDir>/src/pagination/$1",
    "@router/(.+)": "<rootDir>/src/router/$1",
    "@signalR/(.+)": "<rootDir>/src/signalR/$1",
    "@store/(.+)": "<rootDir>/src/store/$1",
    "@theme/(.+)": "<rootDir>/src/theme/$1",
    "@utils/(.+)": "<rootDir>/src/utils/$1",
    "@validation/(.+)": "<rootDir>/src/validation/$1",
    "@ui-kit/(.+)": "<rootDir>/src/ui-kit/$1",
  },
};
