import { Links } from "@enums/links";
import { INews } from "@enums/slices";
import { mapNews } from "@mappers/news";

const newsArr: INews[] = [
  {
    id: 1,
    title: "Заголовок новости #1",
    description: "Какое то описание для примера",
    newsDate: new Date().toString(),
    text: "",
    color: "light",
    news_type: "bishkek",
    images: [],
    banners: {
      id: 1,
      banner: Links.jalAcademy,
      createdAt: "1232131",
      updatedAt: "1232131",
      description: "dawdaw",
      link: "dawdaw",
      title: "121312",
    },
    createdAt: new Date().toString(),
    updatedAt: new Date().toString(),
    videos: {
      id: 1,
      createdAt: new Date().toString(),
      updatedAt: "1232131",
      preview_path: "awdaw",
      video: "dawdaw",
    },
  },
  {
    id: 2,
    title: "Заголовок новости #2",
    description: "Какое то описание для примера",
    text: "",
    color: "light",
    news_type: "bishkek",
    images: [],
    banners: {
      id: 2,
      banner: Links.jalAcademy,
      createdAt: "1232131",
      updatedAt: "1232131",
      description: "dawdaw",
      link: "dawdaw",
      title: "121312",
    },
    createdAt: new Date().toString(),
    updatedAt: new Date().toString(),
    videos: {
      id: 2,
      createdAt: new Date().toString(),
      updatedAt: "1232131",
      preview_path: "awdaw",
      video: "dawdaw",
    },
  },
  {
    id: 3,
    title: "Заголовок новости #3",
    description: "Какое то описание для примера",
    newsDate: new Date().toString(),
    text: "",
    color: "light",
    news_type: "bishkek",
    images: [],
    banners: {
      id: 3,
      banner: Links.jalAcademy,
      createdAt: "1232131",
      updatedAt: "1232131",
      description: "dawdaw",
      link: "dawdaw",
      title: "121312",
    },
    createdAt: new Date().toString(),
    updatedAt: new Date().toString(),
    videos: {
      id: 3,
      createdAt: new Date().toString(),
      updatedAt: "1232131",
      preview_path: "awdaw",
      video: "dawdaw",
    },
  },
  {
    id: 4,
    title: "Заголовок новости #4",
    description: "Какое то описание для примера",
    newsDate: new Date().toString(),
    text: "",
    color: "light",
    news_type: "bishkek",
    images: [],
    banners: {
      id: 4,
      banner: Links.jalAcademy,
      createdAt: "1232131",
      updatedAt: "1232131",
      description: "dawdaw",
      link: "dawdaw",
      title: "121312",
    },
    createdAt: new Date().toString(),
    updatedAt: new Date().toString(),
    videos: {
      id: 4,
      createdAt: new Date().toString(),
      updatedAt: "1232131",
      preview_path: "awdaw",
      video: "dawdaw",
    },
  },
  {
    id: 5,
    title: "Заголовок новости #5",
    description: "Какое то описание для примера",
    newsDate: new Date().toString(),
    text: "",
    color: "light",
    news_type: "bishkek",
    images: [],
    banners: {
      id: 5,
      banner: Links.jalAcademy,
      createdAt: "1232131",
      updatedAt: "1232131",
      description: "dawdaw",
      link: "dawdaw",
      title: "121312",
    },
    createdAt: new Date().toString(),
    updatedAt: new Date().toString(),
    videos: {
      id: 5,
      createdAt: new Date().toString(),
      updatedAt: "1232131",
      preview_path: "awdaw",
      video: "dawdaw",
    },
  },
  {
    id: 6,
    title: "Заголовок новости #6",
    description: "Какое то описание для примера",
    newsDate: new Date().toString(),
    text: "",
    color: "light",
    news_type: "bishkek",
    images: [],
    banners: {
      id: 6,
      banner: Links.jalAcademy,
      createdAt: "1232131",
      updatedAt: "1232131",
      description: "dawdaw",
      link: "dawdaw",
      title: "121312",
    },
    createdAt: new Date().toString(),
    updatedAt: new Date().toString(),
    videos: {
      id: 6,
      createdAt: new Date().toString(),
      updatedAt: "1232131",
      preview_path: "awdaw",
      video: "dawdaw",
    },
  },
  {
    id: 7,
    title: "Заголовок новости #7",
    description: "Какое то описание для примера",
    newsDate: new Date().toString(),
    text: "",
    color: "light",
    news_type: "bishkek",
    images: [],
    banners: {
      id: 7,
      banner: Links.jalAcademy,
      createdAt: "1232131",
      updatedAt: "1232131",
      description: "dawdaw",
      link: "dawdaw",
      title: "121312",
    },
    createdAt: new Date().toString(),
    updatedAt: new Date().toString(),
    videos: {
      id: 7,
      createdAt: new Date().toString(),
      updatedAt: "1232131",
      preview_path: "awdaw",
      video: "dawdaw",
    },
  },
  {
    id: 8,
    title: "Заголовок новости #8",
    description: "Какое то описание для примера",
    newsDate: new Date().toString(),
    text: "",
    color: "light",
    news_type: "bishkek",
    images: [],
    banners: {
      id: 8,
      banner: Links.jalAcademy,
      createdAt: "1232131",
      updatedAt: "1232131",
      description: "dawdaw",
      link: "dawdaw",
      title: "121312",
    },
    createdAt: new Date().toString(),
    updatedAt: new Date().toString(),
    videos: {
      id: 8,
      createdAt: new Date().toString(),
      updatedAt: "1232131",
      preview_path: "awdaw",
      video: "dawdaw",
    },
  },
];

export const newsArray = mapNews(newsArr);
